spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:blog-api
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true